name: 'Upload Applivery'
description: 'Upload React Native builds to Applivery'
inputs:
  api-key:
    description: 'Applivery API Key'
    required: true
  app-file:
    description: 'Path to build file (.apk or .ipa)'
    required: true
  notify:
    description: 'Notify'
    required: false
    default: false
  tags:
    description: 'List of tags, in CSV (e.g. production,english)'
    required: true
  changelog:
    description: 'changelog, A string that includes the date, pull request number, pull request name (optional), commit, version, build type, environment. (05_08_23 PR 2707 Commit fd51f5b v0.1.0 Alpha KDV13)'
    required: true
  github-tag:
    description: 'Github tag'
    required: false
  version: 
    description: 'app version'
    required: true


runs:
  using: 'composite'
  steps:
    - name: Upload to Applivery
      shell: bash
      env:
        API_KEY: ${{ inputs.api-key }}
        APP_FILE: ${{ inputs.app-file }}
        NOTIFY: ${{ inputs.notify }}
        TAGS: ${{ inputs.tags }}
        CHANGELOG: ${{ inputs.changelog }}
        GITHUB_TAG: ${{ inputs.github-tag }}
        VERSION: ${{ inputs.version }}

        # GITHUB_TAG: ${{ github.ref }}
      run: ${{ github.action_path }}/upload-applivery.sh
