name: 'Upload Applivery'
description: 'Upload React Native builds to Applivery'
inputs:
  api-key:
    description: 'Applivery API Key'
    required: true
  app-file:
    description: 'Path to build file (.apk or .ipa)'
    required: true
  notify:
    description: 'Notify'
    required: false
    default: 'on'
  tags:
    description: 'List of tags, in CSV (e.g. production,english)'
    required: false
  release-notes:
    description: 'Release notes'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Upload to Applivery
      shell: bash
      env:
        API_KEY: ${{ inputs.api-key }}
        APP_FILE: ${{ inputs.app-file }}
        NOTIFY: ${{ inputs.notify }}
        TAGS: ${{ inputs.tags }}
        RELEASE_NOTES: ${{ inputs.release-notes }}
      run: ${{ github.action_path }}/upload-applivery.sh
